In [1]:
import pandas as pd
import numpy as np

In [11]:
data = pd.read_csv('10Year Swap Rate.csv')
data

,Start Date,USSWAP1 Curncy,USSWAP2 Curncy,USSWAP3 Curncy,USSWAP4 Curncy,USSWAP5 Curncy,USSWAP6 Curncy,USSWAP7 Curncy,USSWAP10 Curncy,USSWAP9 Curncy,USSWAP10 Curncy.1,USSWAP11 Curncy,USSWAP12 Curncy,USSWAP15 Curncy,USSWAP20 Curncy,USSWAP25 Curncy,USSWAP30 Curncy,USSWAP40 Curncy,USSWAP50 Curncy
0,2006-08-31,5.38150,5.29150,5.20050,5.17450,5.15050,5.15500,5.15800,5.17000,5.18050,5.19150,5.20300,5.21550,5.22800,5.25750,5.28750,5.27750,5.26700,5.27700
1,2006-09-01,5.37100,5.26600,5.18100,5.15850,5.13600,5.13850,5.14100,5.15400,5.16700,5.17850,5.19000,5.20350,5.21700,5.24900,5.28100,5.27000,5.25900,5.27000
2,2006-09-04,5.37100,5.26350,5.17450,5.15150,5.13000,5.13600,5.14200,5.15600,5.17000,5.18300,5.19600,5.19600,5.19600,5.23600,5.27600,5.27925,5.26250,5.25925
3,2006-09-05,5.39000,5.30200,5.21350,5.19000,5.16900,5.17400,5.17700,5.18850,5.20000,5.21450,5.22900,5.24300,5.25500,5.28450,5.31550,5.30500,5.29500,5.30550
4,2006-09-06,5.39800,5.31150,5.22700,5.20300,5.18100,5.18600,5.18850,5.20100,5.21350,5.22850,5.24350,5.25300,5.26250,5.29500,5.32750,5.31700,5.30650,5.31700
5,2006-09-07,5.39850,5.30700,5.23200,5.20850,5.18700,5.18850,5.17950,5.19750,5.20800,5.22050,5.23300,5.24400,5.25500,5.28600,5.31650,5.29550,5.29250,5.31350
6,2006-09-08,5.39900,5.31250,5.22750,5.20300,5.17500,5.17650,5.17950,5.19150,5.20300,5.21350,5.22400,5.23550,5.24750,5.27750,5.30750,5.29800,5.28700,5.29650
7,2006-09-11,5.41800,5.33450,5.25500,5.22900,5.20250,5.20350,5.20500,5.21600,5.22550,5.23900,5.25100,5.26100,5.27200,5.30350,5.33400,5.32300,5.31300,5.32400
8,2006-09-12,5.40850,5.32400,5.23850,5.20800,5.17950,5.17900,5.17900,5.19050,5.19900,5.21000,5.22200,5.23350,5.24500,5.27500,5.30400,5.29500,5.28500,5.29400
9,2006-09-13,5.39600,5.30650,5.21850,5.19200,5.16600,5.16750,5.16500,5.17750,5.19150,5.20200,5.21150,5.22150,5.23300,5.26250,5.29150,5.28200,5.27300,5.28250
10,2006-09-14,5.42700,5.34350,5.25900,5.23150,5.20450,5.20550,5.20600,5.21800,5.23000,5.24200,5.25300,5.26250,5.27250,5.29950,5.32700,5.31750,5.30800,5.31750
11,2006-09-15,5.44700,5.36550,5.28750,5.25850,5.23000,5.23100,5.23100,5.24050,5.24850,5.25800,5.26800,5.27700,5.28550,5.31100,5.33650,5.32950,5.32150,5.32850
12,2006-09-18,5.45700,5.37150,5.30500,5.28700,5.25350,5.25200,5.25100,5.25950,5.26700,5.27850,5.28900,5.29650,5.30350,5.32850,5.35350,5.34550,5.33800,5.34600
13,2006-09-19,5.40300,5.31350,5.22600,5.18800,5.16800,5.17650,5.17600,5.18650,5.18800,5.19800,5.20800,5.21750,5.22650,5.25450,5.28300,5.27350,5.26400,5.27350
14,2006-09-20,5.41000,5.31900,5.23000,5.19950,5.17050,5.16900,5.16800,5.17750,5.18500,5.19600,5.20700,5.21450,5.22350,5.25000,5.27700,5.26900,5.25950,5.26750
15,2006-09-21,5.32350,5.21500,5.10550,5.07300,5.04350,5.04650,5.04750,5.05950,5.07150,5.08300,5.09400,5.10500,5.11650,5.14700,5.17750,5.16800,5.15800,5.16750
16,2006-09-22,5.30000,5.19150,5.08500,5.05150,5.01600,5.01450,5.01250,5.02000,5.02650,5.03700,5.04850,5.05800,5.06800,5.09700,5.12550,5.11650,5.10700,5.11600
17,2006-09-25,5.27350,5.15950,5.04500,5.00850,4.97250,4.96850,4.96350,4.96950,4.97650,4.98750,4.99750,5.00650,5.01500,5.04100,5.06800,5.06000,5.05100,5.05900
18,2006-09-26,5.30500,5.20100,5.09700,5.05350,5.02800,5.03450,5.02250,5.02950,5.03500,5.04300,5.05350,5.06200,5.06900,5.09300,5.11800,5.11050,5.10200,5.10950
19,2006-09-27,5.30300,5.19200,5.08300,5.05150,5.01850,5.01800,5.01650,5.02300,5.03150,5.04350,5.05400,5.06200,5.07050,5.09850,5.12600,5.11650,5.10750,5.11700
20,2006-09-28,5.30350,5.19500,5.08900,5.05950,5.02800,5.02700,5.02650,5.03550,5.04350,5.05450,5.06650,5.07650,5.08600,5.11550,5.14400,5.13450,5.12400,5.13350
21,2006-09-29,5.31400,5.21150,5.11200,5.08350,5.05450,5.05600,5.05600,5.06500,5.07400,5.08500,5.09650,5.10450,5.11300,5.14100,5.16900,5.16000,5.15050,5.15950
22,2006-10-02,5.28500,5.17600,5.06750,5.03400,5.00950,5.00900,5.01000,5.03050,5.04000,5.05050,5.06300,5.07350,5.08400,5.11550,5.14750,5.13700,5.12700,5.13750
23,2006-10-03,5.28600,5.17950,5.07600,5.05050,5.02350,5.02650,5.02850,5.03850,5.04950,5.06100,5.07300,5.08500,5.09600,5.12450,5.15450,5.14450,5.13300,5.14300
24,2006-10-04,5.23200,5.11550,4.99950,4.97200,4.94450,4.94950,4.95250,4.96500,4.97750,4.99000,5.00350,5.01550,5.02750,5.06000,5.09300,5.08250,5.07150,5.08200
25,2006-10-05,5.27600,5.16800,5.06100,5.03300,5.00650,5.00100,5.00550,5.02450,5.03300,5.04550,5.05800,5.06950,5.08050,5.11200,5.14350,5.13300,5.12250,5.13300
26,2006-10-06,5.33100,5.24150,5.15500,5.12300,5.10800,5.11300,5.11700,5.12750,5.13900,5.16000,5.16400,5.17350,5.18300,5.21050,5.23800,5.22850,5.21900,5.22850
27,2006-10-09,5.33100,5.23550,5.15000,5.13200,5.11400,5.11600,5.11800,5.12750,5.13700,5.14850,5.16000,5.17050,5.18100,5.21000,5.23900,5.22900,5.21900,5.22900
28,2006-10-10,5.37500,5.30250,5.23200,5.21150,5.19150,5.19500,5.19800,5.20750,5.21750,5.22800,5.23850,5.24750,5.25650,5.28300,5.30850,5.29950,5.29150,5.30050
29,2006-10-11,5.39700,5.32900,5.26150,5.24500,5.22600,5.22800,5.23000,5.23800,5.24700,5.25650,5.26650,5.27650,5.28500,5.30800,5.33300,5.32500,5.31650,5.32450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2580,2016-07-21,0.86150,0.90795,0.95500,0.98890,1.02370,1.05595,1.08800,1.12070,1.15260,1.18765,1.22300,1.25830,1.29370,1.38155,1.46990,1.44285,1.41605,1.44310
2581,2016-07-22,0.87000,0.91770,0.96705,1.00280,1.03930,1.07310,1.10575,1.13810,1.17000,1.20490,1.23975,1.27260,1.30690,1.39250,1.47830,1.45230,1.42650,1.45250
2582,2016-07-25,0.89100,0.94075,0.99100,1.02690,1.06200,1.09475,1.12860,1.16105,1.19300,1.22620,1.25900,1.28965,1.32250,1.40520,1.48800,1.46265,1.43730,1.46265
2583,2016-07-26,0.88070,0.92620,0.97100,1.00490,1.03950,1.07170,1.10390,1.13640,1.16900,1.20235,1.23525,1.26680,1.29870,1.38200,1.46525,1.43975,1.41435,1.43985
2584,2016-07-27,0.86950,0.90785,0.94770,0.97715,1.00650,1.03390,1.06100,1.08935,1.11750,1.14935,1.18050,1.21065,1.24200,1.32300,1.40390,1.37890,1.35400,1.37900
2585,2016-07-28,0.85400,0.88960,0.92580,0.95585,0.98660,1.01685,1.04675,1.07750,1.10800,1.14085,1.17300,1.20375,1.23575,1.31805,1.40050,1.37575,1.35000,1.37475
2586,2016-07-29,0.82450,0.85235,0.88050,0.90675,0.93325,0.96130,0.99050,1.02185,1.05200,1.08590,1.11900,1.15060,1.18300,1.26795,1.35200,1.32590,1.29975,1.32585
2587,2016-08-01,0.84500,0.87685,0.90875,0.93750,0.96770,1.00005,1.03250,1.06800,1.10250,1.13865,1.17400,1.20705,1.24175,1.33020,1.41800,1.39095,1.36405,1.39110
2588,2016-08-02,0.85900,0.89020,0.92275,0.95320,0.98400,1.01820,1.05250,1.08930,1.12500,1.16240,1.19900,1.23325,1.26925,1.35925,1.44900,1.42195,1.39500,1.42205
2589,2016-08-03,0.87400,0.90135,0.92925,0.95660,0.98375,1.01460,1.04650,1.08120,1.11500,1.15200,1.18825,1.22270,1.25825,1.34850,1.43785,1.41050,1.38300,1.41035
2590,2016-08-04,0.86600,0.88860,0.91300,0.93670,0.96090,0.98895,1.01750,1.05065,1.08175,1.11645,1.15100,1.18445,1.22000,1.30830,1.39665,1.36985,1.34250,1.36930
2591,2016-08-05,0.91550,0.95225,0.99100,1.02230,1.05400,1.08625,1.11770,1.15165,1.18500,1.21890,1.25200,1.28335,1.31550,1.39705,1.47950,1.45470,1.42950,1.45430
2592,2016-08-08,0.93050,0.96925,1.00850,1.04050,1.07330,1.10425,1.13450,1.16645,1.19880,1.23230,1.26500,1.29610,1.32760,1.40805,1.48825,1.46380,1.43950,1.46395
2593,2016-08-09,0.92950,0.96210,0.99475,1.02155,1.04950,1.07710,1.10400,1.13335,1.16300,1.19420,1.22450,1.25385,1.28380,1.36010,1.43850,1.41545,1.39125,1.41430
2594,2016-08-10,0.90395,0.93245,0.96150,0.98580,1.01080,1.03780,1.06400,1.09250,1.12150,1.15240,1.18250,1.21195,1.24150,1.31820,1.39675,1.37275,1.34900,1.37300
2595,2016-08-11,0.92450,0.96135,0.99850,1.02765,1.05700,1.08525,1.11350,1.14245,1.17200,1.20220,1.23150,1.26105,1.29070,1.36680,1.44290,1.41965,1.39700,1.42025
2596,2016-08-12,0.89350,0.92610,0.95950,0.98560,1.01180,1.03845,1.06500,1.09355,1.12225,1.15295,1.18300,1.21280,1.24270,1.32030,1.39800,1.37460,1.35100,1.37440
2597,2016-08-15,0.88600,0.92265,0.95950,0.98930,1.01950,1.05040,1.08150,1.11330,1.14525,1.17860,1.21105,1.24240,1.27420,1.35480,1.43550,1.41140,1.38690,1.41100
2598,2016-08-16,0.90000,0.93890,0.97825,1.00870,1.03950,1.06975,1.10000,1.13115,1.16240,1.19410,1.22500,1.25460,1.28450,1.36130,1.43850,1.41540,1.39200,1.41510
2599,2016-08-17,0.90460,0.94005,0.97600,1.00520,1.03450,1.06385,1.09300,1.12275,1.15275,1.18365,1.21400,1.24300,1.27250,1.34770,1.42250,1.39990,1.37740,1.40000
2600,2016-08-18,0.89650,0.92870,0.96150,0.98850,1.01580,1.04535,1.07500,1.10525,1.13550,1.16710,1.19800,1.22785,1.25800,1.33540,1.41300,1.38950,1.36600,1.38950
2601,2016-08-19,0.92500,0.96260,1.00100,1.03165,1.06125,1.09120,1.12120,1.15030,1.18005,1.21050,1.24020,1.26860,1.29705,1.36940,1.44220,1.42055,1.39840,1.42005
2602,2016-08-22,0.92950,0.96160,0.99400,1.01965,1.04600,1.07260,1.09925,1.12585,1.15250,1.18080,1.20850,1.23505,1.26175,1.33095,1.40050,1.38005,1.35950,1.37995
2603,2016-08-23,0.93150,0.96560,0.99975,1.02605,1.05250,1.07750,1.10300,1.12930,1.15565,1.18370,1.21100,1.23735,1.26425,1.33240,1.40050,1.38030,1.36000,1.38020
2604,2016-08-24,0.92000,0.95395,0.98850,1.01580,1.04350,1.07090,1.09850,1.12665,1.15475,1.18470,1.21400,1.24195,1.27050,1.34090,1.41225,1.39060,1.36950,1.39115
2605,2016-08-25,0.93800,0.97605,1.01500,1.04395,1.07500,1.10325,1.13050,1.15860,1.18575,1.21480,1.24300,1.26990,1.29800,1.36565,1.43525,1.41530,1.39425,1.41420
2606,2016-08-26,0.97350,1.01940,1.06620,1.09920,1.13200,1.16255,1.19300,1.22100,1.24900,1.27770,1.30600,1.33195,1.35825,1.42305,1.48825,1.46935,1.45025,1.46915
2607,2016-08-29,0.95200,0.99180,1.03225,1.06015,1.08800,1.11375,1.13950,1.16450,1.18950,1.21540,1.24100,1.26525,1.29000,1.35250,1.41475,1.39615,1.37760,1.39620
2608,2016-08-30,0.95500,0.99530,1.03650,1.06575,1.09500,1.12185,1.14850,1.17410,1.20000,1.22630,1.25200,1.27670,1.30200,1.36510,1.42800,1.40890,1.38990,1.40900
2609,2016-08-31,0.96600,1.00870,1.05225,1.08260,1.11300,1.14070,1.16820,1.19415,1.22045,1.24680,1.27300,1.29770,1.32250,1.38490,1.44725,1.42855,1.40990,1.42860

In [20]:
title = data.columns[1:].values

In [21]:
data
data = np.array(data)
data

array([['2006-08-31', 5.3815, 5.2915, ..., 5.2775, 5.267,
        5.276999999999999],
       ['2006-09-01', 5.371, 5.266, ..., 5.27, 5.2589999999999995, 5.27],
       ['2006-09-04', 5.371, 5.2635000000000005, ..., 5.27925, 5.2625,
        5.25925],
       ...,
       ['2016-08-29', 0.9520000000000001, 0.9918, ..., 1.39615, 1.3776,
        1.3962],
       ['2016-08-30', 0.955, 0.9953, ..., 1.4089, 1.3899, 1.409],
       ['2016-08-31', 0.966, 1.0087000000000002, ..., 1.42855, 1.4099,
        1.4286]], dtype=object)

In [35]:
currency = 'USD'
index = 'US swap'


dat = []
for i in range(len(data)):
    dat_day = np.zeros(shape = (len(data[0])-1+4,2)).astype('O')
    dat_day[:4,0] = ['CCY','INDEX','DATE','ID']
    dat_day[:4,1] = [currency, index, data[:,0][i], 'TEAM3']
    dat_day[4:,0] = title
    dat_day[4:,1] = data[i][1:]
    dat.append(dat_day)

In [36]:
dat

[array([['CCY', 'USD'],
        ['INDEX', 'US swap'],
        ['DATE', '2006-08-31'],
        ['ID', 'TEAM3'],
        ['USSWAP1 Curncy', 5.3815],
        ['USSWAP2 Curncy', 5.2915],
        ['USSWAP3 Curncy', 5.2005],
        ['USSWAP4 Curncy', 5.1745],
        ['USSWAP5 Curncy', 5.1505],
        ['USSWAP6 Curncy', 5.1549999999999985],
        ['USSWAP7 Curncy', 5.158],
        ['USSWAP10 Curncy', 5.17],
        ['USSWAP9 Curncy', 5.1805],
        ['USSWAP10 Curncy.1', 5.1915],
        ['USSWAP11 Curncy', 5.2029999999999985],
        ['USSWAP12 Curncy', 5.2155000000000005],
        ['USSWAP15 Curncy', 5.228],
        ['USSWAP20 Curncy', 5.2575],
        ['USSWAP25 Curncy', 5.2875],
        ['USSWAP30 Curncy', 5.2775],
        ['USSWAP40 Curncy', 5.267],
        ['USSWAP50 Curncy', 5.276999999999999]], dtype=object),
 array([['CCY', 'USD'],
        ['INDEX', 'US swap'],
        ['DATE', '2006-09-01'],
        ['ID', 'TEAM3'],
        ['USSWAP1 Curncy', 5.371],
        ['USSWAP2 Curncy', 5.266],
        ['USSWAP3 Curncy', 5.180999999999999],
        ['USSWAP4 Curncy', 5.1585],
        ['USSWAP5 Curncy', 5.135999999999999],
        ['USSWAP6 Curncy', 5.1385000000000005],
        ['USSWAP7 Curncy', 5.141],
        ['USSWAP10 Curncy', 5.154],
        ['USSWAP9 Curncy', 5.167000000000001],
        ['USSWAP10 Curncy.1', 5.1785],
        ['USSWAP11 Curncy', 5.19],
        ['USSWAP12 Curncy', 5.2035],
        ['USSWAP15 Curncy', 5.2170000000000005],
        ['USSWAP20 Curncy', 5.2490000000000006],
        ['USSWAP25 Curncy', 5.2810000000000015],
        ['USSWAP30 Curncy', 5.27],
        ['USSWAP40 Curncy', 5.2589999999999995],
        ['USSWAP50 Curncy', 5.27]], dtype=object),
 array([['CCY', 'USD'],
        ['INDEX', 'US swap'],
        ['DATE', '2006-09-04'],
        ['ID', 'TEAM3'],
        ['USSWAP1 Curncy', 5.371],
        ['USSWAP2 Curncy', 5.2635000000000005],
        ['USSWAP3 Curncy', 5.1745],
        ['USSWAP4 Curncy', 5.1515],
        ['USSWAP5 Curncy', 5.130000000000001],
        ['USSWAP6 Curncy', 5.136],
        ['USSWAP7 Curncy', 5.142],
        ['USSWAP10 Curncy', 5.1560000000000015],
        ['USSWAP9 Curncy', 5.17],
        ['USSWAP10 Curncy.1', 5.183],
        ['USSWAP11 Curncy', 5.196000000000001],
        ['USSWAP12 Curncy', 5.196000000000001],
        ['USSWAP15 Curncy', 5.196000000000001],
        ['USSWAP20 Curncy', 5.2360000000000015],
        ['USSWAP25 Curncy', 5.276],
        ['USSWAP30 Curncy', 5.27925],
        ['USSWAP40 Curncy', 5.2625],
        ['USSWAP50 Curncy', 5.25925]], dtype=object),
 array([['CCY', 'USD'],
        ['INDEX', 'US swap'],
        ['DATE', '2006-09-05'],
        ['ID', 'TEAM3'],
        ['USSWAP1 Curncy', 5.3900000000000015],
        ['USSWAP2 Curncy', 5.3020000000000005],
        ['USSWAP3 Curncy', 5.2135],
        ['USSWAP4 Curncy', 5.19],
        ['USSWAP5 Curncy', 5.1690000000000005],
        ['USSWAP6 Curncy', 5.174],
        ['USSWAP7 Curncy', 5.1770000000000005],
        ['USSWAP10 Curncy', 5.1885],
        ['USSWAP9 Curncy', 5.2],
        ['USSWAP10 Curncy.1', 5.2145],
        ['USSWAP11 Curncy', 5.229],
        ['USSWAP12 Curncy', 5.242999999999999],
        ['USSWAP15 Curncy', 5.255],
        ['USSWAP20 Curncy', 5.2845],
        ['USSWAP25 Curncy', 5.3155],
        ['USSWAP30 Curncy', 5.305],
        ['USSWAP40 Curncy', 5.295],
        ['USSWAP50 Curncy', 5.3055]], dtype=object),
 array([['CCY', 'USD'],
        ['INDEX', 'US swap'],
        ['DATE', '2006-09-06'],
        ['ID', 'TEAM3'],
        ['USSWAP1 Curncy', 5.398],
        ['USSWAP2 Curncy', 5.3115],
        ['USSWAP3 Curncy', 5.227],
        ['USSWAP4 Curncy', 5.2029999999999985],
        ['USSWAP5 Curncy', 5.180999999999999],
        ['USSWAP6 Curncy', 5.186],
        ['USSWAP7 Curncy', 5.1885],
        ['USSWAP10 Curncy', 5.2010000000000005],
        ['USSWAP9 Curncy', 5.2135],
        ['USSWAP10 Curncy.1', 5.2285],
        ['USSWAP11 Curncy', 5.2435],
        ['USSWAP12 Curncy', 5.252999999999999],
        ['USSWAP15 Curncy', 5.2625],
        ['USSWAP20 Curncy', 5.295],
        ['USSWAP25 Curncy', 5.3275],
        ['USSWAP30 Curncy', 5.317],
        ['USSWAP40 Curncy', 5.3065],
        ['USSWAP50 Curncy', 5.317]], dtype=object),
 array([['CCY', 'USD'],
        ['INDEX', 'US swap'],
        ['DATE', '2006-09-07'],
        ['ID', 'TEAM3'],
        ['USSWAP1 Curncy', 5.3985],
        ['USSWAP2 Curncy', 5.307],
        ['USSWAP3 Curncy', 5.232],
        ['USSWAP4 Curncy', 5.2085],
        ['USSWAP5 Curncy', 5.1869999999999985],
        ['USSWAP6 Curncy', 5.1885],
        ['USSWAP7 Curncy', 5.1795],
        ['USSWAP10 Curncy', 5.1975],
        ['USSWAP9 Curncy', 5.207999999999999],
        ['USSWAP10 Curncy.1', 5.2205],
        ['USSWAP11 Curncy', 5.2330000000000005],
        ['USSWAP12 Curncy', 5.244],
        ['USSWAP15 Curncy', 5.255],
        ['USSWAP20 Curncy', 5.2860000000000005],
        ['USSWAP25 Curncy', 5.3165],
        ['USSWAP30 Curncy', 5.2955],
        ['USSWAP40 Curncy', 5.2925],
        ['USSWAP50 Curncy', 5.3135]], dtype=object),
 array([['CCY', 'USD'],
        ['INDEX', 'US swap'],
        ['DATE', '2006-09-08'],
        ['ID', 'TEAM3'],
        ['USSWAP1 Curncy', 5.399],
        ['USSWAP2 Curncy', 5.3125],
        ['USSWAP3 Curncy', 5.2275],
        ['USSWAP4 Curncy', 5.2029999999999985],
        ['USSWAP5 Curncy', 5.175],
        ['USSWAP6 Curncy', 5.1765],
        ['USSWAP7 Curncy', 5.1795],
        ['USSWAP10 Curncy', 5.1915],
        ['USSWAP9 Curncy', 5.2029999999999985],
        ['USSWAP10 Curncy.1', 5.2135],
        ['USSWAP11 Curncy', 5.224],
        ['USSWAP12 Curncy', 5.2355],
        ['USSWAP15 Curncy', 5.2475000000000005],
        ['USSWAP20 Curncy', 5.2775],
        ['USSWAP25 Curncy', 5.3075],
        ['USSWAP30 Curncy', 5.297999999999999],
        ['USSWAP40 Curncy', 5.287000000000001],
        ['USSWAP50 Curncy', 5.2965]], dtype=object),
 array([['CCY', 'USD'],
        ['INDEX', 'US swap'],
        ['DATE', '2006-09-11'],
        ['ID', 'TEAM3'],
        ['USSWAP1 Curncy', 5.417999999999999],
        ['USSWAP2 Curncy', 5.3345],
        ['USSWAP3 Curncy', 5.255000000000001],
        ['USSWAP4 Curncy', 5.229],
        ['USSWAP5 Curncy', 5.2025000000000015],
        ['USSWAP6 Curncy', 5.2035],
        ['USSWAP7 Curncy', 5.205],
        ['USSWAP10 Curncy', 5.215999999999998],
        ['USSWAP9 Curncy', 5.2255],
        ['USSWAP10 Curncy.1', 5.239],
        ['USSWAP11 Curncy', 5.251],
        ['USSWAP12 Curncy', 5.260999999999999],
        ['USSWAP15 Curncy', 5.272],
        ['USSWAP20 Curncy', 5.3035],
        ['USSWAP25 Curncy', 5.334],
        ['USSWAP30 Curncy', 5.3229999999999995],
        ['USSWAP40 Curncy', 5.3130000000000015],
        ['USSWAP50 Curncy', 5.324]], dtype=object),
 array([['CCY', 'USD'],
        ['INDEX', 'US swap'],
        ['DATE', '2006-09-12'],
        ['ID', 'TEAM3'],
        ['USSWAP1 Curncy', 5.4085],
        ['USSWAP2 Curncy', 5.324],
        ['USSWAP3 Curncy', 5.2385],
        ['USSWAP4 Curncy', 5.207999999999999],
        ['USSWAP5 Curncy', 5.1795],
        ['USSWAP6 Curncy', 5.178999999999999],
        ['USSWAP7 Curncy', 5.178999999999999],
        ['USSWAP10 Curncy', 5.1905],
        ['USSWAP9 Curncy', 5.199],
        ['USSWAP10 Curncy.1', 5.21],
        ['USSWAP11 Curncy', 5.222],
        ['USSWAP12 Curncy', 5.2335],
        ['USSWAP15 Curncy', 5.245],
        ['USSWAP20 Curncy', 5.275],
        ['USSWAP25 Curncy', 5.303999999999999],
        ['USSWAP30 Curncy', 5.295],
        ['USSWAP40 Curncy', 5.285],
        ['USSWAP50 Curncy', 5.2940000000000005]], dtype=object),
 array([['CCY', 'USD'],
        ['INDEX', 'US swap'],
        ['DATE', '2006-09-13'],
        ['ID', 'TEAM3'],
        ['USSWAP1 Curncy', 5.396],
        ['USSWAP2 Curncy', 5.3065],
        ['USSWAP3 Curncy', 5.2185000000000015],
        ['USSWAP4 Curncy', 5.192],
        ['USSWAP5 Curncy', 5.166],
        ['USSWAP6 Curncy', 5.1675],
        ['USSWAP7 Curncy', 5.165],
        ['USSWAP10 Curncy', 5.1775],
        ['USSWAP9 Curncy', 5.1915],
        ['USSWAP10 Curncy.1', 5.202000000000001],
        ['USSWAP11 Curncy', 5.2115],
        ['USSWAP12 Curncy', 5.2215],
        ['USSWAP15 Curncy', 5.2330000000000005],
        ['USSWAP20 Curncy', 5.2625],
        ['USSWAP25 Curncy', 5.2915],
        ['USSWAP30 Curncy', 5.282],
        ['USSWAP40 Curncy', 5.273],
        ['USSWAP50 Curncy', 5.2825000000000015]], dtype=object),
 array([['CCY', 'USD'],
        ['INDEX', 'US swap'],
        ['DATE', '2006-09-14'],
        ['ID', 'TEAM3'],
        ['USSWAP1 Curncy', 5.4270000000000005],
        ['USSWAP2 Curncy', 5.3435],
        ['USSWAP3 Curncy', 5.2589999999999995],
        ['USSWAP4 Curncy', 5.2315000000000005],
        ['USSWAP5 Curncy', 5.2045],
        ['USSWAP6 Curncy', 5.2055],
        ['USSWAP7 Curncy', 5.206],
        ['USSWAP10 Curncy', 5.218],
        ['USSWAP9 Curncy', 5.23],
        ['USSWAP10 Curncy.1', 5.242000000000001],
        ['USSWAP11 Curncy', 5.252999999999999],
        ['USSWAP12 Curncy', 5.262499999999998],
        ['USSWAP15 Curncy', 5.2725],
        ['USSWAP20 Curncy', 5.2995],
        ['USSWAP25 Curncy', 5.327000000000001],
        ['USSWAP30 Curncy', 5.3175],
        ['USSWAP40 Curncy', 5.308],
        ['USSWAP50 Curncy', 5.3175]], dtype=object),
 array([['CCY', 'USD'],
        ['INDEX', 'US swap'],
        ['DATE', '2006-09-15'],
        ['ID', 'TEAM3'],
        ['USSWAP1 Curncy', 5.447],
        ['USSWAP2 Curncy', 5.3655],
        ['USSWAP3 Curncy', 5.2875],
        ['USSWAP4 Curncy', 5.2585],
        ['USSWAP5 Curncy', 5.23],
        ['USSWAP6 Curncy', 5.231],
        ['USSWAP7 Curncy', 5.231],
        ['USSWAP10 Curncy', 5.2405],
        ['USSWAP9 Curncy', 5.2485],
        ['USSWAP10 Curncy.1', 5.257999999999999],
        ['USSWAP11 Curncy', 5.268],
        ['USSWAP12 Curncy', 5.276999999999999],
        ['USSWAP15 Curncy', 5.2855],
        ['USSWAP20 Curncy', 5.311],
        ['USSWAP25 Curncy', 5.3365],
        ['USSWAP30 Curncy', 5.3295],
        ['USSWAP40 Curncy', 5.3215],
        ['USSWAP50 Curncy', 5.3285]], dtype=object),
 array([['CCY', 'USD'],
        ['INDEX', 'US swap'],
        ['DATE', '2006-09-18'],
        ['ID', 'TEAM3'],
        ['USSWAP1 Curncy', 5.457000000000001],
        ['USSWAP2 Curncy', 5.371499999999998],
        ['USSWAP3 Curncy', 5.305],
        ['USSWAP4 Curncy', 5.287000000000001],
        ['USSWAP5 Curncy', 5.2535],
        ['USSWAP6 Curncy', 5.252000000000001],
        ['USSWAP7 Curncy', 5.251],
        ['USSWAP10 Curncy', 5.2595],
        ['USSWAP9 Curncy', 5.267],
        ['USSWAP10 Curncy.1', 5.278499999999998],
        ['USSWAP11 Curncy', 5.289],
        ['USSWAP12 Curncy', 5.2965],
        ['USSWAP15 Curncy', 5.3035],
        ['USSWAP20 Curncy', 5.3285],
        ['USSWAP25 Curncy', 5.3535],
        ['USSWAP30 Curncy', 5.3455],
        ['USSWAP40 Curncy', 5.337999999999999],
        ['USSWAP50 Curncy', 5.346]], dtype=object),
 array([['CCY', 'USD'],
        ['INDEX', 'US swap'],
        ['DATE', '2006-09-19'],
        ['ID', 'TEAM3'],
        ['USSWAP1 Curncy', 5.4030000000000005],
        ['USSWAP2 Curncy', 5.3135],
        ['USSWAP3 Curncy', 5.226],
        ['USSWAP4 Curncy', 5.188],
        ['USSWAP5 Curncy', 5.167999999999998],
        ['USSWAP6 Curncy', 5.1765],
        ['USSWAP7 Curncy', 5.176],
        ['USSWAP10 Curncy', 5.1865000000000006],
        ['USSWAP9 Curncy', 5.1880000000000015],
        ['USSWAP10 Curncy.1', 5.1979999999999995],
        ['USSWAP11 Curncy', 5.207999999999999],
        ['USSWAP12 Curncy', 5.2174999999999985],
        ['USSWAP15 Curncy', 5.2265],
        ['USSWAP20 Curncy', 5.2545],
        ['USSWAP25 Curncy', 5.283],
        ['USSWAP30 Curncy', 5.2735],
        ['USSWAP40 Curncy', 5.263999999999999],
        ['USSWAP50 Curncy', 5.2735]], dtype=object),
 array([['CCY', 'USD'],
        ['INDEX', 'US swap'],
        ['DATE', '2006-09-20'],
        ['ID', 'TEAM3'],
        ['USSWAP1 Curncy', 5.41],
        ['USSWAP2 Curncy', 5.319],
        ['USSWAP3 Curncy', 5.23],
        ['USSWAP4 Curncy', 5.1995000000000005],
        ['USSWAP5 Curncy', 5.1705000000000005],
        ['USSWAP6 Curncy', 5.1690000000000005],
        ['USSWAP7 Curncy', 5.167999999999998],
        ['USSWAP10 Curncy', 5.1775],
        ['USSWAP9 Curncy', 5.1850000000000005],
        ['USSWAP10 Curncy.1', 5.196000000000001],
        ['USSWAP11 Curncy', 5.207000000000001],
        ['USSWAP12 Curncy', 5.214499999999999],
        ['USSWAP15 Curncy', 5.2235],
        ['USSWAP20 Curncy', 5.25],
        ['USSWAP25 Curncy', 5.276999999999999],
        ['USSWAP30 Curncy', 5.269],
        ['USSWAP40 Curncy', 5.2595],
        ['USSWAP50 Curncy', 5.2675]], dtype=object),
 array([['CCY', 'USD'],
        ['INDEX', 'US swap'],
        ['DATE', '2006-09-21'],
        ['ID', 'TEAM3'],
        ['USSWAP1 Curncy', 5.3235],
        ['USSWAP2 Curncy', 5.215],
        ['USSWAP3 Curncy', 5.1055],
        ['USSWAP4 Curncy', 5.073],
        ['USSWAP5 Curncy', 5.0435],
        ['USSWAP6 Curncy', 5.0465],
        ['USSWAP7 Curncy', 5.0475],
        ['USSWAP10 Curncy', 5.0595],
        ['USSWAP9 Curncy', 5.0715],
        ['USSWAP10 Curncy.1', 5.083],
        ['USSWAP11 Curncy', 5.0939999999999985],
        ['USSWAP12 Curncy', 5.105],
        ['USSWAP15 Curncy', 5.1165],
        ['USSWAP20 Curncy', 5.147],
        ['USSWAP25 Curncy', 5.1775],
        ['USSWAP30 Curncy', 5.167999999999999],
        ['USSWAP40 Curncy', 5.158],
        ['USSWAP50 Curncy', 5.1675]], dtype=object),
 array([['CCY', 'USD'],
        ['INDEX', 'US swap'],
        ['DATE', '2006-09-22'],
        ['ID', 'TEAM3'],
        ['USSWAP1 Curncy', 5.3],
        ['USSWAP2 Curncy', 5.1915],
        ['USSWAP3 Curncy', 5.085000000000001],
        ['USSWAP4 Curncy', 5.051500000000001],
        ['USSWAP5 Curncy', 5.016],
        ['USSWAP6 Curncy', 5.0145],
        ['USSWAP7 Curncy', 5.0125],
        ['USSWAP10 Curncy', 5.02],
        ['USSWAP9 Curncy', 5.0265],
        ['USSWAP10 Curncy.1', 5.037],
        ['USSWAP11 Curncy', 5.0485],
        ['USSWAP12 Curncy', 5.058],
        ['USSWAP15 Curncy', 5.0680000000000005],
        ['USSWAP20 Curncy', 5.097],
        ['USSWAP25 Curncy', 5.1255],
        ['USSWAP30 Curncy', 5.1165],
        ['USSWAP40 Curncy', 5.106999999999998],
        ['USSWAP50 Curncy', 5.1160000000000005]], dtype=object),
 array([['CCY', 'USD'],
        ['INDEX', 'US swap'],
        ['DATE', '2006-09-25'],
        ['ID', 'TEAM3'],
        ['USSWAP1 Curncy', 5.2735],
        ['USSWAP2 Curncy', 5.1595],
        ['USSWAP3 Curncy', 5.045],
        ['USSWAP4 Curncy', 5.0085],
        ['USSWAP5 Curncy', 4.9725],
        ['USSWAP6 Curncy', 4.9685],
        ['USSWAP7 Curncy', 4.9635],
        ['USSWAP10 Curncy', 4.9695],
        ['USSWAP9 Curncy', 4.9765],
        ['USSWAP10 Curncy.1', 4.987500000000002],
        ['USSWAP11 Curncy', 4.9975000000000005],
        ['USSWAP12 Curncy', 5.0065],
        ['USSWAP15 Curncy', 5.0150000000000015],
        ['USSWAP20 Curncy', 5.041],
        ['USSWAP25 Curncy', 5.0680000000000005],
        ['USSWAP30 Curncy', 5.0600000000000005],
        ['USSWAP40 Curncy', 5.051],
        ['USSWAP50 Curncy', 5.058999999999998]], dtype=object),
 array([['CCY', 'USD'],
        ['INDEX', 'US swap'],
        ['DATE', '2006-09-26'],
        ['ID', 'TEAM3'],
        ['USSWAP1 Curncy', 5.305],
        ['USSWAP2 Curncy', 5.2010000000000005],
        ['USSWAP3 Curncy', 5.097],
        ['USSWAP4 Curncy', 5.0535],
        ['USSWAP5 Curncy', 5.0280000000000005],
        ['USSWAP6 Curncy', 5.0345],
        ['USSWAP7 Curncy', 5.0225],
        ['USSWAP10 Curncy', 5.0295000000000005],
        ['USSWAP9 Curncy', 5.035],
        ['USSWAP10 Curncy.1', 5.043],
        ['USSWAP11 Curncy', 5.0535],
        ['USSWAP12 Curncy', 5.0619999999999985],
        ['USSWAP15 Curncy', 5.069],
        ['USSWAP20 Curncy', 5.093],
        ['USSWAP25 Curncy', 5.118],
        ['USSWAP30 Curncy', 5.1105],
        ['USSWAP40 Curncy', 5.102],
        ['USSWAP50 Curncy', 5.1095]], dtype=object),
 array([['CCY', 'USD'],
        ['INDEX', 'US swap'],
        ['DATE', '2006-09-27'],
        ['ID', 'TEAM3'],
        ['USSWAP1 Curncy', 5.303],
        ['USSWAP2 Curncy', 5.192],
        ['USSWAP3 Curncy', 5.083],
        ['USSWAP4 Curncy', 5.0515],
        ['USSWAP5 Curncy', 5.0185],
        ['USSWAP6 Curncy', 5.018],
        ['USSWAP7 Curncy', 5.0165],
        ['USSWAP10 Curncy', 5.023],
        ['USSWAP9 Curncy', 5.0314999999999985],
        ['USSWAP10 Curncy.1', 5.0435],
        ['USSWAP11 Curncy', 5.053999999999999],
        ['USSWAP12 Curncy', 5.0619999999999985],
        ['USSWAP15 Curncy', 5.0705],
        ['USSWAP20 Curncy', 5.0985],
        ['USSWAP25 Curncy', 5.126],
        ['USSWAP30 Curncy', 5.1165],
        ['USSWAP40 Curncy', 5.1075],
        ['USSWAP50 Curncy', 5.117]], dtype=object),
 array([['CCY', 'USD'],
        ['INDEX', 'US swap'],
        ['DATE', '2006-09-28'],
        ['ID', 'TEAM3'],
        ['USSWAP1 Curncy', 5.3035],
        ['USSWAP2 Curncy', 5.195],
        ['USSWAP3 Curncy', 5.0889999999999995],
        ['USSWAP4 Curncy', 5.0595],
        ['USSWAP5 Curncy', 5.0280000000000005],
        ['USSWAP6 Curncy', 5.027],
        ['USSWAP7 Curncy', 5.0265],
        ['USSWAP10 Curncy', 5.0355],
        ['USSWAP9 Curncy', 5.0435],
        ['USSWAP10 Curncy.1', 5.0545],
        ['USSWAP11 Curncy', 5.0665],
        ['USSWAP12 Curncy', 5.0764999999999985],
        ['USSWAP15 Curncy', 5.086],
        ['USSWAP20 Curncy', 5.1155],
        ['USSWAP25 Curncy', 5.144],
        ['USSWAP30 Curncy', 5.134499999999999],
        ['USSWAP40 Curncy', 5.124],
        ['USSWAP50 Curncy', 5.1335]], dtype=object),
 array([['CCY', 'USD'],
        ['INDEX', 'US swap'],
        ['DATE', '2006-09-29'],
        ['ID', 'TEAM3'],
        ['USSWAP1 Curncy', 5.314],
        ['USSWAP2 Curncy', 5.2115],
        ['USSWAP3 Curncy', 5.112],
        ['USSWAP4 Curncy', 5.0835],
        ['USSWAP5 Curncy', 5.0545],
        ['USSWAP6 Curncy', 5.056],
        ['USSWAP7 Curncy', 5.056],
        ['USSWAP10 Curncy', 5.065],
        ['USSWAP9 Curncy', 5.074],
        ['USSWAP10 Curncy.1', 5.085],
        ['USSWAP11 Curncy', 5.0965],
        ['USSWAP12 Curncy', 5.1045],
        ['USSWAP15 Curncy', 5.113],
        ['USSWAP20 Curncy', 5.141],
        ['USSWAP25 Curncy', 5.1690000000000005],
        ['USSWAP30 Curncy', 5.16],
        ['USSWAP40 Curncy', 5.1505],
        ['USSWAP50 Curncy', 5.1595]], dtype=object),
 array([['CCY', 'USD'],
        ['INDEX', 'US swap'],
        ['DATE', '2006-10-02'],
        ['ID', 'TEAM3'],
        ['USSWAP1 Curncy', 5.285],
        ['USSWAP2 Curncy', 5.176],
        ['USSWAP3 Curncy', 5.0675],
        ['USSWAP4 Curncy', 5.034],
        ['USSWAP5 Curncy', 5.0095],
        ['USSWAP6 Curncy', 5.0089999999999995],
        ['USSWAP7 Curncy', 5.01],
        ['USSWAP10 Curncy', 5.0305],
        ['USSWAP9 Curncy', 5.04],
        ['USSWAP10 Curncy.1', 5.0505],
        ['USSWAP11 Curncy', 5.0630000000000015],
        ['USSWAP12 Curncy', 5.0735],
        ['USSWAP15 Curncy', 5.084],
        ['USSWAP20 Curncy', 5.1155],
        ['USSWAP25 Curncy', 5.1475],
        ['USSWAP30 Curncy', 5.1370000000000005],
        ['USSWAP40 Curncy', 5.127000000000001],
        ['USSWAP50 Curncy', 5.137499999999998]], dtype=object),
 array([['CCY', 'USD'],
        ['INDEX', 'US swap'],
        ['DATE', '2006-10-03'],
        ['ID', 'TEAM3'],
        ['USSWAP1 Curncy', 5.2860000000000005],
        ['USSWAP2 Curncy', 5.1795],
        ['USSWAP3 Curncy', 5.0760000000000005],
        ['USSWAP4 Curncy', 5.0505],
        ['USSWAP5 Curncy', 5.0235],
        ['USSWAP6 Curncy', 5.0265],
        ['USSWAP7 Curncy', 5.028499999999998],
        ['USSWAP10 Curncy', 5.0385],
        ['USSWAP9 Curncy', 5.0495],
        ['USSWAP10 Curncy.1', 5.061],
        ['USSWAP11 Curncy', 5.073],
        ['USSWAP12 Curncy', 5.085],
        ['USSWAP15 Curncy', 5.096],
        ['USSWAP20 Curncy', 5.1245],
        ['USSWAP25 Curncy', 5.1545000000000005],

In [38]:
import codecs



f = codecs.open("test.txt",'w','utf-8')


#f.write(str(list))
for i in dat:
    f.write(str(i)+'\r\n')  #\r\n为换行符

f.close()